version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  nginx:
      image: nginx
      volumes:
      - ${PWD}/server.crt:/etc/nginx/conf.d/server.crt:ro
      - ${PWD}/server.key:/etc/nginx/conf.d/server.key:ro
      - ${PWD}/default.conf:/etc/nginx/conf.d/default.conf
      ports:
      - 443:443
      - 80:80
  keycloak:
      #image: quay.io/keycloak/keycloak:16.1.1
      image: quay.io/keycloak/keycloak:17.0.1
      #command: ["start-dev","--http-relative-path /auth"]
      command: ["start", "--auto-build","--cache-stack=kubernetes"]
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        KC_HTTP_RELATIVE_PATH: /auth
        KC_PROXY: edge
        KC_HOSTNAME: test2
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: password
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
        JAVA_OPTS_APPEND: "-Djgroups.dns.query=keycloak"
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 8080:8080
        - 8443:8443
      depends_on:
        - postgres